an:
  main: 99
  frontpage: 100
ar:
  main: 53
  frontpage: 100
be_BY:
  main: 98
  frontpage: 100
bg_BG:
  main: 44
  frontpage: 18
ca:
  main: 83
  frontpage: 81
cmn:
  main: 31
  frontpage: 0
cs:
  main: 84
  frontpage: 100
da:
  main: 99
  frontpage: 100
de:
  main: 99
  frontpage: 100
el:
  main: 100
  frontpage: 100
eo:
  main: 97
  frontpage: 100
es:
  main: 99
  frontpage: 100
fa_IR:
  main: 13
  frontpage: 100
fi:
  main: 7
  frontpage: 0
fr:
  main: 98
  frontpage: 100
ga_IE:
  main: 48
  frontpage: 37
gl:
  main: 75
  frontpage: 51
he:
  main: 71
  frontpage: 100
hr:
  main: 50
  frontpage: 100
hu:
  main: 100
  frontpage: 100
id:
  main: 57
  frontpage: 51
it:
  main: 98
  frontpage: 100
it_CH:
  main: 0
  frontpage: 0
ja:
  main: 68
  frontpage: 62
km:
  main: 52
  frontpage: 0
ko:
  main: 61
  frontpage: 97
lv:
  main: 0
  frontpage: 0
mi:
  main: 0
  frontpage: 2
mk:
  main: 58
  frontpage: 100
ml:
  main: 56
  frontpage: 0
nl_NL:
  main: 99
  frontpage: 100
pl:
  main: 19
  frontpage: 100
pt_BR:
  main: 100
  frontpage: 100
pt_PT:
  main: 10
  frontpage: 25
ro:
  main: 99
  frontpage: 100
ru:
  main: 56
  frontpage: 100
sk:
  main: 100
  frontpage: 100
sl:
  main: 21
  frontpage: 100
sr:
  main: 100
  frontpage: 100
sr_RS:
  main: 100
  frontpage: 100
sv:
  main: 73
  frontpage: 100
te:
  main: 28
  frontpage: 18
tr:
  main: 100
  frontpage: 100
uk:
  main: 64
  frontpage: 83
ur:
  main: 0
  frontpage: 0
ur_PK:
  main: 0
  frontpage: 0
vi:
  main: 46
  frontpage: 0
zh_TW:
  main: 100
  frontpage: 100
